PyCity/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('tutorials.urls')),  # strona glowna + poradniki
    url(r'^forum/', include('pybb.urls', namespace='pybb')),
    url(r'^user/', include('user.urls')),

    # admin
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybb/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

tutorials/urls.py
from . import views
from django.conf.urls import url
from django.core.urlresolvers import reverse
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^poradniki$', views.kategorie, name='kats'),
    url(r'^poradniki/(?P<kat_id>[0-9]+)/$', views.show_tuts, name='tuts'),
    url(r'^poradniki/(\d)/(?P<tut_id>[0-9]+)$', views.show_tut, name='tut'),
    url(r'^img/(?P<img_id>[0-9]+)$', views.img, name='img'),
    #url(r'^666$', RedirectView.as_view(url=reverse('admin:index')), name='admin'),
]

tutorials/models.py
from django.db import models
from user.models import Profile

# Tutorials/models.py
# Create your models here.


class Kategoria(models.Model):
    nazwa = models.CharField(max_length=40)
    opis = models.TextField(default="-- Brak opisu --")

    def __str__(self):
        return self.nazwa


class Poradnik(models.Model):
    kategoria = models.ForeignKey(Kategoria, default=0)
    tytul = models.CharField(max_length=150)
    tresc = models.TextField()
    opis = models.CharField(max_length=150, default="")

    PYTHON2 = "P2"
    PYTHON3 = "P3"
    PYTHON = "PP"

    VERSIONS = (
        (PYTHON2, 'Python 2.7'),
        (PYTHON3, 'Python 3.5'),
        (PYTHON, 'Python 2.7 and 3.5'),
    )

    version = models.CharField(
        max_length=2,
        choices=VERSIONS,
        default=PYTHON,
    )

    def __str__(self):
        return '{} | {}'.format(self.kategoria.nazwa, self.tytul)


class Image(models.Model):
    poradnik = models.ForeignKey(Poradnik)
    nazwa = models.CharField(max_length=40, default="", blank=True)

    def upload_location(self, filename):
        url = 'tuts/{}/{}'.format(str(self.poradnik.pk), str(filename))
        return url

    image = models.ImageField(
        upload_to=upload_location
    )

    def __str__(self):
        return 'Kategoria: {} Tutorial:{}. {} Image: {}'.format(
            self.poradnik.kategoria.nazwa, self.poradnik.pk,
            self.poradnik.tytul, self.nazwa)


class File(models.Model):
    poradnik = models.ForeignKey(Poradnik, blank=True)
    nazwa = models.CharField(max_length=40, default="", blank=True)

    def upload_location(self, filename):
        if self.poradnik.pk:
            url = 'files/{}/{}'.format(str(self.poradnik.pk), str(filename))
        else:
            url = 'files/{}/{}'.format(str(filename))
        return url

tutorials/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from .models import Kategoria, Poradnik, Image
from django.contrib.auth.models import User
from django.shortcuts import get_list_or_404, get_object_or_404

# Create your views here.


# wymagany do poprawnego działania side baru
def nav(request):
    if request.user.is_authenticated():
        try:
            avatar = '/media{}'.format(request.user.profile.avatar.url.split('media')[-1])
        except:
            avatar = '/media/default.png'

        idict = {
            'is_logged': True,
            'user': request.user,
            'avatar': avatar
        }
        return idict
    else:
        idict = {
            'is_logged': False
        }
        return idict


def home(request):
    idict = nav(request)
    return render(request, 'tutorials/home.html', {
        'idict': idict,
        'title': 'PyCity - Naucz się pythona!'
    })


def kategorie(request):
    idict = nav(request)
    kats = Kategoria.objects.all()
    return render(request, 'tutorials/kategorie.html', {
        'kategorie': kats,
        'idict': idict
    })


def show_tuts(request, kat_id):
    idict = nav(request)
    tuts = get_list_or_404(Poradnik, kategoria=kat_id)
    return render(request, 'tutorials/poradniki.html', {
        'idict': idict,
        'tuts': tuts
    })


def show_tut(request, tut_id):
    idict = nav(request)
    tuts = get_list_or_404(Poradnik, pk=tut_id)
    imgs = Image.objects.filter(poradnik=tut_id)
    return render(request, 'tutorials/poradnik.html', {
        'idict': idict,
        'tut': tuts,
        'img': imgs,
    })


def img(request, img_id):
    img = get_object_or_404(Image, pk=img_id)
    return render(request, 'tutorials/img.html', {
        'img': img
    })

tutorials/templates/tutorials/headers/header.html
<!DOCTYPE html>
<html>
<head lang="pl">
    <meta charset="UTF-8">
    <meta name="keywords" content="Python, django, poradnik, darmowy poradnik">

    <title>{{ title }}</title>

    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% load staticfiles %}
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png"> <!-- favicon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/materialize.min.css' %}" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
    <!--Import jQuery before materialize.js-->
        {% load staticfiles %}
        <script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/header.js' %}"></script>

    {% include 'tutorials/snippets/sidenav.html' %}

    <header class="row blue darken-3 white-text valign-wrapper">
        <div class="col s2 m2 l2">
            {% if idict.is_logged %}
            <a href="#" data-activates="slide-out" class="button-collapse">
                <span class="small material-icons white-text flow-text valign">reorder</span><span><b class="valign txt">{{ idict.user.username }}</b></span>
            </a>
            {% else %}
            <a href="{% url 'Login' %}" class="valign-wrapper"><span class="material-icons valign">perm_identity</span><b class="valign txt">Zaloguj się!</b></a>
            {% endif %}
        </div>
        <div class="col s10 m8 l6 offset-m3 offset-l6 valign-wrapper">
            <span class="flow-text valign">PyCity - Naucz się pythona!</span>
            <span><img src="{% static 'img/djangopony.png' %}"> </span>
            <span><img src="{% static 'img/python-HE.png' %}"> </span>
        </div>
    </header>
    <header class="row blue-grey darken-4" id="2">
        <nav class="col s12 m8 l8 offset-m2 offset-l2 blue-grey darken-4 white-text ">
            <a href="{% url 'home' %}"><span class="col s4 center-align truncate">Strona główna</span></a>
            <a href="{% url 'kats' %}"><span class="col s4 center-align">Poradniki</span></a>
            <a href="{% url 'pybb:index' %}"><span class="col s4 center-align">Forum</span></a>
        </nav>
    </header>
    <main class="row">
        <div class="col s12 m12 l12">
            {% block content %}
            {% endblock %}
        </div>
    </main>

</body>
</html>