PyCity/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('tutorials.urls')),  # strona glowna + poradniki
    url(r'^forum/', include('pybb.urls', namespace='pybb')),
    url(r'^user/', include('user.urls')),

    # admin
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybb/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

pybb/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import math

from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.exceptions import PermissionDenied, ValidationError
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db.models import F, Q
from django.forms.utils import ErrorList
from django.http import HttpResponseRedirect, HttpResponse, Http404, HttpResponseBadRequest,\
    HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic.edit import ModelFormMixin
from django.views.decorators.csrf import csrf_protect
from django.views import generic
from pybb import compat, defaults, util
from pybb.compat import get_atomic_func
from pybb.forms import PostForm, AdminPostForm, AttachmentFormSet, \
    PollAnswerFormSet, PollForm, ForumSubscriptionForm, ModeratorForm
from pybb.models import Category, Forum, ForumSubscription, Topic, Post, TopicReadTracker, \
    ForumReadTracker, PollAnswerUser
from pybb.permissions import perms
from pybb.templatetags.pybb_tags import pybb_topic_poll_not_voted


User = compat.get_user_model()
username_field = compat.get_username_field()
Paginator, pure_pagination = compat.get_paginator_class()


class PaginatorMixin(object):
    def get_paginator(self, queryset, per_page, orphans=0, allow_empty_first_page=True, **kwargs):
        kwargs = {}
        if pure_pagination:
            kwargs['request'] = self.request
        return Paginator(queryset, per_page, orphans=0, allow_empty_first_page=True, **kwargs)


class RedirectToLoginMixin(object):
    """ mixin which redirects to settings.LOGIN_URL if the view encounters an PermissionDenied exception
        and the user is not authenticated. Views inheriting from this need to implement
        get_login_redirect_url(), which returns the URL to redirect to after login (parameter "next")
    """
    def dispatch(self, request, *args, **kwargs):
        try:
            return super(RedirectToLoginMixin, self).dispatch(request, *args, **kwargs)
        except PermissionDenied:
            if not request.user.is_authenticated():
                from django.contrib.auth.views import redirect_to_login
                return redirect_to_login(self.get_login_redirect_url())
            else:
                return HttpResponseForbidden()

    def get_login_redirect_url(self):
        """ get the url to which we redirect after the user logs in. subclasses should override this """
        return '/'


class IndexView(generic.ListView):

    template_name = 'pybb/index.html'
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        ctx = super(IndexView, self).get_context_data(**kwargs)
        categories = ctx['categories']
        for category in categories:
            category.forums_accessed = perms.filter_forums(self.request.user, category.forums.filter(parent=None))
        ctx['categories'] = categories
        return ctx

    def get_queryset(self):
        return perms.filter_categories(self.request.user, Category.objects.all())


class CategoryView(RedirectToLoginMixin, generic.DetailView):

    template_name = 'pybb/index.html'
    context_object_name = 'category'

    def get_login_redirect_url(self):
        # returns super.get_object as there is a conflict with the perms in CategoryView.get_object
        # Would raise a PermissionDenied and never redirect
        return super(CategoryView, self).get_object().get_absolute_url()

    def get_queryset(self):
        return Category.objects.all()

    def get_object(self, queryset=None):
        obj = super(CategoryView, self).get_object(queryset)
        if not perms.may_view_category(self.request.user, obj):
            raise PermissionDenied
        return obj

    def get_context_data(self, **kwargs):
        ctx = super(CategoryView, self).get_context_data(**kwargs)
        ctx['category'].forums_accessed = perms.filter_forums(self.request.user, ctx['category'].forums.filter(parent=None))
        ctx['categories'] = [ctx['category']]
        return ctx

    def get(self, *args, **kwargs):
        if defaults.PYBB_NICE_URL and (('id' in kwargs) or ('pk' in kwargs)):
            return redirect(super(CategoryView, self).get_object(), permanent=defaults.PYBB_NICE_URL_PERMANENT_REDIRECT)
        return super(CategoryView, self).get(*args, **kwargs)


class ForumView(RedirectToLoginMixin, PaginatorMixin, generic.ListView):

    paginate_by = defaults.PYBB_FORUM_PAGE_SIZE
    context_object_name = 'topic_list'
    template_name = 'pybb/forum.html'

    def dispatch(self, request, *args, **kwargs):
        self.forum = self.get_forum(**kwargs)
        return super(ForumView, self).dispatch(request, *args, **kwargs)

    def get_login_redirect_url(self):
        return self.forum.get_absolute_url()

    def get_context_data(self, **kwargs):
        ctx = super(ForumView, self).get_context_data(**kwargs)
        ctx['forum'] = self.forum
        if self.request.user.is_authenticated():
            try:
                ctx['subscription'] = ForumSubscription.objects.get(
                    user=self.request.user,
                    forum=self.forum
                )
            except ForumSubscription.DoesNotExist:
                ctx['subscription'] = None
        else:
            ctx['subscription'] = None
        ctx['forum'].forums_accessed = perms.filter_forums(self.request.user, self.forum.child_forums.all())
        return ctx

    def get_queryset(self):
        if not perms.may_view_forum(self.request.user, self.forum):
            raise PermissionDenied

        qs = self.forum.topics.order_by('-sticky', '-updated', '-id').select_related()
        qs = perms.filter_topics(self.request.user, qs)
        return qs

    def get_forum(self, **kwargs):
        if 'pk' in kwargs:
            forum = get_object_or_404(Forum.objects.all(), pk=kwargs['pk'])
        elif ('slug' and 'category_slug') in kwargs:
            forum = get_object_or_404(Forum, slug=kwargs['slug'], category__slug=kwargs['category_slug'])
        else:
            raise Http404(_('Forum does not exist'))
        return forum

    def get(self, *args, **kwargs):
        if defaults.PYBB_NICE_URL and 'pk' in kwargs:
            return redirect(self.forum, permanent=defaults.PYBB_NICE_URL_PERMANENT_REDIRECT)
        return super(ForumView, self).get(*args, **kwargs)


class ForumSubscriptionView(RedirectToLoginMixin, generic.FormView):
    template_name = 'pybb/forum_subscription.html'
    form_class = ForumSubscriptionForm

    def get_login_redirect_url(self):
        return reverse('pybb:forum_subscription', args=(self.kwargs['pk'],))

    def get_success_url(self):
        return self.forum.get_absolute_url()

    def get_form_kwargs(self):
        kw = super(ForumSubscriptionView, self).get_form_kwargs()
        self.get_objects()
        kw['instance'] = self.forum_subscription
        kw['user'] = self.request.user
        kw['forum'] = self.forum
        return kw

    def get_context_data(self, **kwargs):
        ctx = super(ForumSubscriptionView, self).get_context_data(**kwargs)
        ctx['forum'] = self.forum
        ctx['forum_subscription'] = self.forum_subscription
        return ctx

    def form_valid(self, form):
        result = form.process()
        if result == 'subscribe-all':
            msg = _((
                'Zasubskrybowałeś wszystkie istniejące tematy na tym forum '
                'oraz wszystkie przyszłe tematy będą subskrybowane automatycznie'
            ))
        elif result == 'delete':
            msg = _((
                'Nie będziesz więcej informowany o każdym nowym temacie '
                'założonym na tym forum.'
            ))
        elif result == 'delete-all':
            msg = _((
                'Zasubskrybowałeś każdy obecny temat na tym forum, ale nie będziesz '
                'otrzymywał powiadomień o nowo utworzonych tematach.'
            ))
        else:
            msg = _((
                'Będziesz powiadamiany za każdym razem kiedy nowy temat zostanie utworzony na tym forum.'
            ))
        messages.success(self.request, msg, fail_silently=True)
        return super(ForumSubscriptionView, self).form_valid(form)

    def get_objects(self):
        if not self.request.user.is_authenticated():
            raise PermissionDenied
        self.forum = get_object_or_404(Forum.objects.all(), pk=self.kwargs['pk'])
        try:
            self.forum_subscription = ForumSubscription.objects.get(
                user=self.request.user,
                forum=self.forum
            )
        except ForumSubscription.DoesNotExist:
            self.forum_subscription = None

class LatestTopicsView(PaginatorMixin, generic.ListView):

    paginate_by = defaults.PYBB_FORUM_PAGE_SIZE
    context_object_name = 'topic_list'
    template_name = 'pybb/latest_topics.html'

    def get_queryset(self):
        qs = Topic.objects.all().select_related()
        qs = perms.filter_topics(self.request.user, qs)
        return qs.order_by('-updated', '-id')


class PybbFormsMixin(object):

    post_form_class = PostForm
    admin_post_form_class = AdminPostForm
    attachment_formset_class = AttachmentFormSet
    poll_form_class = PollForm
    poll_answer_formset_class = PollAnswerFormSet

    def get_post_form_class(self):
        return self.post_form_class

    def get_admin_post_form_class(self):
        return self.admin_post_form_class

    def get_attachment_formset_class(self):
        return self.attachment_formset_class

    def get_poll_form_class(self):
        return self.poll_form_class

    def get_poll_answer_formset_class(self):
        return self.poll_answer_formset_class

pybb/templates/pybb/markup/bbcode_widget.html
{% load i18n %}

{{ widget_output }}

<script type="text/javascript">
if(!window.pybb){
    window.pybb = {};
}
if(!window.pybb.get_markitup_settings){
    window.pybb.get_markitup_settings = function() {
        var mySettings = new Array();
        mySettings['previewParserPath'] = '{% url "pybb:post_ajax_preview" %}';
        mySettings['previewPosition'] = 'before';
        mySettings['resizeHandle'] = true;
        mySettings['markupSet'] = [
            {name:'{% trans "Bold" %}', key:'B', openWith:'[b]', closeWith:'[/b]'},
            {name:'{% trans "Italic" %}', key:'I', openWith:'[i]', closeWith:'[/i]'},
            {name:'{% trans "Underline" %}', key:'U', openWith:'[u]', closeWith:'[/u]'},
            {name:'{% trans "Stroke" %}', key:'S', openWith:'[s]', closeWith:'[/s]'},
            {separator:'---------------' },
            {name:'{% trans "Picture" %}', key:'P', replaceWith:'[img][![Url]!][/img]'},
            {name:'{% trans "Link" %}', key:'L', openWith:'[url=[![Url]!]]', closeWith:'[/url]', placeHolder:'{% trans "Your text to link here..." %}'},
            {separator:'---------------' },
            {name:'{% trans "Bulleted list" %}', openWith:'[list]\n', closeWith:'\n[/list]'},
            {name:'{% trans "Numeric list" %}', openWith:'[list=[![Starting number]!]]\n', closeWith:'\n[/list]'},
            {name:'{% trans "List item" %}', openWith:'[*] '},
            {separator:'---------------' },
            {name:'{% trans "Quotes" %}', openWith:'[quote]', closeWith:'[/quote]'},
            {name:'{% trans "Code" %}', openWith:'[code]', closeWith:'[/code]'},
            {separator:'---------------' },
            {name:'{% trans "Clean" %}', className:"clean", replaceWith:function(markitup) { return markitup.selection.replace(/\[(.*?)\]/g, "") } },
            {name:'{% trans "Preview" %}', className:"preview", call:'preview' }
        ];
        return mySettings ;
    };
    window.pybb.insert_image = function(url){
        $.markItUp({replaceWith: '[img]'+url+'[/img]'});
    }
    window.pybb.insert_link = function(url, name){
        $.markItUp({replaceWith: '[url='+url+']'+name+'[/url]'});
    }
}

if (!window.pybb.markup) {
    /*
     This object will be used to perform some action specific to the current Markup engine.
     eg : quote button, SHIT + click on an username, etc.
     */
    window.pybb.markup = {
        quote: function (text, username) {
            return '[quote' + (username ? ('="' + username + '"') : '') + ']' + text + '[/quote]\n';
        },
        username: function (username) {
            return '[b]' + username + '[/b], ';
        }
    }
}
</script>

pybb/templates/pybb/markup/markdown_widget.html
{% load i18n %}

{{ widget_output }}


<script type="text/javascript">
if(!window.pybb){
    window.pybb = {};
}
if(!window.pybb.get_markitup_settings){
    window.pybb.get_markitup_settings = function() {
        var mySettings = new Array();
        mySettings['previewParserPath'] = '{% url "pybb:post_ajax_preview" %}';
        mySettings['previewPosition'] = 'before';
        mySettings['resizeHandle'] = true;
        mySettings['markupSet'] = [
            {name:'{% trans "First Level Heading" %}', key:'1', placeHolder:'{% trans "Your title here..." %}', closeWith:function(markItUp) { return miu.markdownTitle(markItUp, '=') } },
            {name:'{% trans "Second Level Heading" %}', key:'2', placeHolder:'{% trans "Your title here..." %}', closeWith:function(markItUp) { return miu.markdownTitle(markItUp, '-') } },
            {name:'{% trans "Heading 3" %}', key:'3', openWith:'### ', placeHolder:'{% trans "Your title here..." %}' },
            {name:'{% trans "Heading 4" %}', key:'4', openWith:'#### ', placeHolder:'{% trans "Your title here..." %}' },
            {name:'{% trans "Heading 5" %}', key:'5', openWith:'##### ', placeHolder:'{% trans "Your title here..." %}' },
            {name:'{% trans "Heading 6" %}', key:'6', openWith:'###### ', placeHolder:'{% trans "Your title here..." %}' },
            {separator:'---------------' },
            {name:'{% trans "Bold" %}', key:'B', openWith:'**', closeWith:'**'},
            {name:'{% trans "Italic" %}', key:'I', openWith:'_', closeWith:'_'},
            {separator:'---------------' },
            {name:'{% trans "Bulleted List" %}', openWith:'- ' },
            {name:'{% trans "Numeric List" %}', openWith:function(markItUp) {
                return markItUp.line+'. ';
            }},
            {separator:'---------------' },
            {name:'{% trans "Picture" %}', key:'P', replaceWith:'![[![Alternative text]!]]([![Url:!:http://]!] "[![Title]!]")'},
            {name:'{% trans "Link" %}', key:'L', openWith:'[', closeWith:']([![Url:!:http://]!] "[![Title]!]")', placeHolder:'{% trans "Your text to link here..." %}' },
            {separator:'---------------'},
            {name:'{% trans "Quotes" %}', openWith:'> '},
            {name:'{% trans "Code Block / Code" %}', openWith:'(!(\t|!|`)!)', closeWith:'(!(`)!)'},
            {separator:'---------------'},
            {name:'{% trans "Preview" %}', call:'preview', className:"preview"}
        ];
        return mySettings ;
    };
    window.pybb.insert_image = function(url){
        $.markItUp({replaceWith: '![]('+url+')'});
    }
    window.pybb.insert_link = function(url, name){
        $.markItUp({replaceWith: '['+name+']('+url+')'});
    }
}

if (!window.pybb.markup) {
    /*
     This object will be used to perform some action specific to the current Markup engine.
     eg : quote button, SHIT + click on an username, etc.
     */
    window.pybb.markup = {
        quote: function (text, username) {
            var output = '';
            if (username) {
                output += '> **' + username + '**: ';
            } else {
                output += '> ';
            }
            output += text.replace(/\n/g, '  \n> ');
            return output;
        },
        username: function (username) {
            return '**' + username + '**, ';
        }
    }
}
</script>